name: Reusable Workflow

on:
  workflow_call:
    inputs:
      input1:
        description: 'VAULT NAMESPACE'
        required: true
        type: string
      input2:
        description: 'VAULT ADDR'
        required: true
        type: string
    outputs:
      output1:
        description: 'First filevalue parameter'
        value: ${{ steps.set-outputs.outputs.filevalue }}
      output2:
        description: 'Second password parameter'
        value: ${{ steps.set-outputs.outputs.password }}
      output3:
        description: 'Third thumbprint parameter'
        value: ${{ steps.set-outputs.outputs.thumbprint }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
