name: Call a reusable workflow and use its outputs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/hashicorp-vault.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.fileValue }} ${{ needs.job1.outputs.password }} ${{ needs.job1.outputs.thumbprint }}