name: Copy Branch to Another Repo

on:
    repository_dispatch:
      types: [branch-copy-event] 

jobs:
  copy-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: gianfra901/automate-templates
          ref: feature/certificate-app-services

      - name: Create branch in destination repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/gianfra901/app1-application.git
          cd app1-application
          git checkout -b feature/${{ github.event.client_payload.jira-issue-id }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/gianfra901/app1-application.git feature/${{ github.event.client_payload.jira-issue-id }}

      - name: Push to destination repository
        env:
          DESTINATION_REPO: https://github.com/gianfra901/app1-application.git
          DESTINATION_BRANCH: feature/${{ github.event.client_payload.jira-issue-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add destino https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/gianfra901/app1-application.git
          git push destino $DESTINATION_BRANCH
