name: Copy Files

on:
    repository_dispatch:
      types: [branch-copy-event] 


jobs:
  copy-files:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        repository: gianfra901/automate-templates
        ref: feature/certificate-app-services  # Cambia esto a la rama que prefieras

    - name: Copy files
      run: |
        rsync -av --progress . ../temp-dir --exclude .git --exclude ../temp-dir

    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: gianfra901/app1-application
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: feature/KAN-43  # Cambia esto a la rama que prefieras

    - name: Copy files to target repository
      run: |
        rsync -av --progress ../temp-dir/ .
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Copy files from source repository"
        git push origin feature/KAN-43
