name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      fileValue:
        description: "Certificate: FileValue base64"
        value: ${{ jobs.example_job.outputs.output1 }}
      password:
        description: "Certificate: Password"
        value: ${{ jobs.example_job.outputs.output2 }}
      thumbprint:
        description: "Certificate: Thumbprint"
        value: ${{ jobs.example_job.outputs.output3 }}        

jobs:
  example_job:
    name: Get Certificate from Hashicorp Vault
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.fileValue }}
      output2: ${{ steps.step2.outputs.password }}
      output3: ${{ steps.step3.outputs.thumbprint }}
    steps:
      - id: step1
        run: echo "fileValue=MIINASDDS...." >> $GITHUB_OUTPUT
      - id: step2
        run: echo "password=Bcp3323" >> $GITHUB_OUTPUT
      - id: step3
        run: echo "thumbprint=AI9823JHEEEW9I221" >> $GITHUB_OUTPUT        