name: Generate Screenshot and Upload to Jira

on:
    workflow_call:
        inputs:
            jira-project-id:
                description: 'Jira Project'
                required: true
                type: string            
            jira-issue:
              description: 'Ticket Jira Issue'
              required: true
              type: string

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: lts/*
        - name: Init npm
          run: npm init -y          
        - name: Install dependencies
          run: npm install --legacy-peer-deps
        - name: Install Playwright Browsers
          run: |
            npm install @playwright/test
            npx playwright install --with-deps
        - name: Run Playwright tests
          run: npx playwright test ./tests/*.spec.ts
        - name: Upload screenshot
          uses: actions/upload-artifact@v4
          with:
            name: screenshot
            path: screenshot.png          

        - name: Upload attachment to Jira
          run: |
            curl -D- -u ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
            -X POST \
            -H "X-Atlassian-Token: no-check" \
            -F "file=@screenshot.png" \
            ${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue/${{ inputs.jira-issue }}/attachments

  jira-create-subtask:
    uses: ./.github/workflows/jira-subtask.yml
    secrets: inherit
    with:
      jira-project-id: ${{ inputs.jira-project-id }}
      jira-issue: ${{ inputs.jira-issue }}
      jira-summary: "[PASPROD] - Implementación de certificado"          
