name: Create Jira Subtask

on:
    workflow_call:
        inputs:
            jira-project-id:
                description: 'Jira Project'
                required: true
                type: string            
            jira-issue:
                description: 'Ticket Jira Issue'
                required: true
                type: string
            jira-summary:
                description: 'Ticket Jira Issue'
                required: true
                type: string                

jobs:
  create-subtask:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Jira Subtask
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        PROJECT_KEY: ${{ inputs.jira-project-id }}
        PARENT_ISSUE_KEY: ${{ inputs.jira-issue }}
        ISSUE_SUMMARY: ${{ inputs.jira-summary }}

      run: |
        response=$(curl -D- -u $JIRA_USER_EMAIL:$JIRA_API_TOKEN -X POST --data '{
          "fields": {
            "project": {
              "key": "'"$PROJECT_KEY"'"
            },            
            "summary": "'"$ISSUE_SUMMARY"'",
            "description": "Description of the subtask",
            "issuetype": {
              "id": "10003"
            },
            "parent": {
              "key": "'"$PARENT_ISSUE_KEY"'"
            }
          }
        }' -H "Content-Type: application/json" $JIRA_BASE_URL/rest/api/2/issue)

        echo "Response: $response"

        issue_key=$(echo $response | jq -r '.key')
        
        echo "Issue Key: $issue_key"
        
        curl -D- -u $JIRA_USER_EMAIL:$JIRA_API_TOKEN -X POST --data '{
          "transition": {
            "id": "10002"
          }
        }' -H "Content-Type: application/json" $JIRA_BASE_URL/rest/api/2/issue/$issue_key/transitions        