name: Delete Files in Master

on:
    repository_dispatch:
      types: [pr-master-to-deploy-event] 

permissions:
  contents: write

jobs:
  delete-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          repository: 'gianfra901/${{ github.event.client_payload.gh-repository-name }}'
          token: ${{ secrets.GH_TOKEN_USER }}
          path: ${{ github.event.client_payload.gh-repository-name }}

      - name: Delete all files except .git
        run: |
          cd ${{ github.event.client_payload.gh-repository-name }}
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          ls -a
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_USER }}

      - name: Commit changes Delete Main
        run: |
          cd ${{ github.event.client_payload.gh-repository-name }}
          ls -a
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Delete all files in main"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_USER }}


      - name: Create Pull Request
        id: create_pr
        run: |
            response=$(curl -s -X POST \
              -H "Authorization: token ${{ secrets.GH_TOKEN_USER }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/gianfra901/${{ github.event.client_payload.gh-repository-name }}/pulls \
              -d '{
                "title": "Automated Pull Request",
                "head": "feature/${{ github.event.client_payload.jira-issue-id }}",
                "base": "main",
                "body": "This pull request contains automated changes."
              }')
            echo "Response: $response"
            pr_number=$(echo "$response" | jq -r '.number')
            echo "::set-output name=pr_number::$pr_number"
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN_USER }} 



      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            repository: gianfra901/${{ github.event.client_payload.gh-repository-name }}
            ref: main
            token: ${{ secrets.GH_TOKEN_USER }}        
  
      - name: Fetch all branches
        run: git fetch https://${{ secrets.GH_TOKEN_USER }}@github.com/gianfra901/${{ github.event.client_payload.gh-repository-name }}.git +refs/pull/*/head:refs/remotes/origin/pull/*/head
        
  
      - name: Checkout PR branch
        run: |
          ls
          git checkout origin/pull/${{ steps.create_pr.outputs.pr_number }}/head
  
      - name: Create temporary merge branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"         
          git checkout -b feature/${{ github.event.client_payload.jira-issue-id }} origin/main
          git merge --allow-unrelated-histories --strategy-option theirs origin/pull/${{ steps.create_pr.outputs.pr_number }}/head
  
      - name: Force push to main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_USER }}
        run: |
          git push https://$GITHUB_TOKEN@github.com/gianfra901/${{ github.event.client_payload.gh-repository-name }} feature/${{ github.event.client_payload.jira-issue-id }}:main --force        